# Generated by Django 5.1.4 on 2024-12-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="shirt_size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="S",
                max_length=1,
            ),
        ),
    ]
