# Generated by Django 5.1.4 on 2024-12-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_person_shirt_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "medal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("BRONZE", "Bronze"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
