# Generated by Django 5.1.4 on 2024-12-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_fruit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
