# Generated by Django 5.1.4 on 2024-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_topping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toppings", models.ManyToManyField(to="app.topping")),
            ],
        ),
    ]
