# Generated by Django 5.1.4 on 2024-12-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_pizza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
    ]
