# Generated by Django 5.1.4 on 2024-12-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(through="app.Membership", to="app.person"),
        ),
        migrations.AddField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(through="app.Membership", to="app.group"),
        ),
    ]
