# Generated by Django 5.1.4 on 2024-12-17 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_group_members_person_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(default=datetime.date(2024, 12, 17)),
        ),
    ]
