# Generated by Django 5.1.4 on 2024-12-17 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
